### ISSUE TITLE
Add result precision processing and comparison among geocoders

### ISSUE THREAD

**Issue by lansman** [geopy/geopy#138]
I suppose this is cornerstone issue of using geocoding at all. Sooner or later every programmer will face that chosen geocoder results won't cover all processed addresses, so he or she has to use several geocoders simultaneously. And at this point it's need to somehow compare results of different geocoders to select the more precision one programmatically.

Geocoders return precision together with coordinates. The problem is every geocoder service has its own precision scale. 
I suggest to create the table for geocoders precisions in csv/sqlite/excel file. Columns are geocoder services, rows are precisions. The intersection of rows/columns contains universal numeric rank, which the lower the better. E.g. 0 - house precision, 100 - street, 200 - district, 300 - city etc

And add this rank value to geopy.location.Location class.

**Comment by KostyaEsmukov** [comment]
This sounds like a very fragile dataset which would significantly increase maintenance burden. It also seems to me like a rare edge case rather than an "every programmer's" challenge.

Sorry, but I'm not willing to support this. Closing, but I'd be happy to come to a compromise if this is still an issue.
