### ISSUE TITLE
Find nearest coords based on user

### ISSUE THREAD

**Issue by kodeine** [geopy/geopy#210]
I am using GeopositionField in Django to store the coordinates of my user. Now I want to find a list of 20 users who are closest to current user. Is this doable via GeoPy?

For example, tinder like matching users.

**Comment by micahcochran** [comment]
This is probably doable in geopy, but I'm not sure how efficient it would be.  

I would suggest trying [rtree](http://toblerity.org/rtree/).  The downside is rtree requires libspatialindex, which is a C library.

**Comment by KostyaEsmukov** [comment]
Computing such thing with geopy would be very inefficient, as it would require `O(N)` calls of the geopy's `distance` method (for each distinct point in the database table).

Instead of GeopositionField, which [stores][geoposition] coordinates as a `CharField`, a much more efficient way would be to use Django's [geospatial fields][geodjango] (which, for example, in Postgres are stored internally as a special [geometry][postgis_addgeom] type and support [geospatial index][postgis_gist]). Then the query would look something like this:

    my_user = User.objects.get(...)
    qs = (
        User.objects.exclude(pk=my_user.pk)
        .annotate(distance=Distance("location", my_user.location))
        .order_by("distance")
    )
    closest_20_users = qs[:20]

However, if you can't use geodjango, you can of course do the computation with geopy, though very inefficiently.

[geoposition]: https://github.com/philippbosch/django-geoposition/blob/b68382b408deb1f9bf62b65050a19fd3cedba775/geoposition/fields.py#L20
[geodjango]: https://docs.djangoproject.com/en/2.0/ref/contrib/gis/model-api/
[postgis_addgeom]: https://postgis.net/docs/AddGeometryColumn.html
[postgis_gist]: https://postgis.net/docs/using_postgis_dbmanagement.html#gist_indexes
