### ISSUE TITLE
parsing text

### ISSUE THREAD

**Issue by EgyxH** [geopy/geopy#235]
so instead of putting values manually am trying to parse it from a text file and store it into variables so I can replace the values in here `location = geolocator.reverse("52.509669, 13.376294")` with `location = geolocator.reverse("x, y")` where x and y are parsed variables from my text file but I get this error 

>   File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/osm.py", line 248, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/base.py", line 158, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQueryError: HTTP Error 400: Bad Request

**Comment by scaars10** [comment]
I am late but you can try this:-
`coord_pair = str(x)+", "+str(y)`
`location = geolocator.reverse(coord_pair)`

**Comment by KostyaEsmukov** [comment]
As [stated in the docs](http://geopy.readthedocs.io/en/1.12.0/#geopy.geocoders.Nominatim.reverse), `reverse` method accepts as query a `Point`, list/tuple or a string.

So the following will work:

```python
location = geolocator.reverse([x, y])
```

PS Next time please consider asking questions at Stack Overflow (with [`geopy` tag](https://stackoverflow.com/questions/tagged/geopy)) instead of reporting them as issues on Github.
