### ISSUE TITLE
Point normalizes latitude bizarrely

### ISSUE THREAD

**Issue by cffk** [geopy/geopy#243]
Point treats latitude periodically and thus connects the north and south
poles

~~~
>>> from geopy import Point
>>> Point(90.1, 10)
Point(-89.9, 10.0, 0.0)
~~~

This can't be considered a sensible result.  Better would be to change
latitudes outside the range [-90, 90] into nans.  Then people who
accidentally switch the order of latitude and longitude will sometimes
get a sharp poke in the eye that they've done something wrong.

**Comment by Serphentas** [comment]
You mean we should raise an exception, or just trim the given value to 90/-90 ?

**Comment by cffk** [comment]
No, I actually meant to convert to NaNs (which would then propagate
through the calculation resulting in a lot of NaNs being generated).
There is no single *right* answer here and certainly either clipping the
result or generating an error might be OK.  The policy might depend on
how the out-of-bounds latitude was generated...  it would be good to
flag errors in user input quickly.  Maybe, a latitude of `90.000001`
resulting from a round-off error can be silently changed to `90` (but I
would also want to see why an invalid latitude was being generated).
That said, I'm sure that changing `90 + eps` to `-90 + eps` (the
current policy) is *wrong*.

**Comment by KostyaEsmukov** [comment]
The current policy, which is to normalize the latitude, is certainly wrong.

As a preliminary step, a warning for that has been added in #272 (`1.13.0`).

In the next minor release (`1.14.0`) I intend to turn this warning to an exception.

The reason why I'd prefer an exception instead of NaNs is that IMO it's more pythonic and easier to handle than NaNs from an API consumer point of view. Also linking a relevant comment of mine: https://github.com/geopy/geopy/issues/242#issuecomment-377886172

**Comment by KostyaEsmukov** [comment]
Opened a #294 PR which addresses that (by replacing warnings with actual exceptions).
