### ISSUE TITLE
geopy ignores altitude when calculating geodesic

### ISSUE THREAD

**Issue by inbaroz** [geopy/geopy#387]
```
import geopy

p1 = geopy.point.Point()
p1.latitude = 10
p1.longitude = -110

p2 = geopy.point.Point()
p2.altitude = 35
p2.latitude = 20
p2.longitude = -120
```

I'm trying to calculate distance between 2 locations. Each location has lat, lon, altitude. When calculating distance using Geopy it doesn't seem to consider the altitude: slight changes in lat, lot influence the result, small/huge change in altitude doesn't affect the resulting distance. 

```
# low alt
p1.altitude = 350 
print(geopy.distance.geodesic(p1, p2).km)
# 1541.8564339502925

# high alt
p1.altitude = 3500000 
print(geopy.distance.geodesic(p1, p2).km)
# 1541.8564339502925
```

**Comment by KostyaEsmukov** [comment]
Indeed, altitude is not considered in distance calculations. 

#165 is also related, but in terms of geocoders.

**Comment by Brootux** [comment]
Ive also run into this. This is a really mean thing which one only figures out after a long time debugging.

**Comment by KostyaEsmukov** [comment]
I see how this can be frustrating. Perhaps in geopy 2.0 it would be possible to start raising an exception when altitudes between two points are different, to explicitly tell that this is not supported.

**Comment by Brootux** [comment]
At least for short 2d distances (i.e. under a kilometer) it would be possible to consider `3d_dist = sqrt(2d_dist² + h_dist²)`

Or is this a bad idea?

**Comment by assulthoni** [comment]
yup i have same issue

**Comment by nachokhan** [comment]
> At least for short 2d distances (e.g. under a kilometer) it would be possible to consider `3d_dist = sqrt(2d_dist² + h_dist²)`
> 
> Or is this a bad idea?

I do exactly this for measuring a more correct distance. I work a lot on mountain environments and it is a muss for me. In a 40km route, you see the difference. I suppose is Ok, because I work with gps samples that are taken 10 m one from each other.

**Comment by KostyaEsmukov** [comment]
> At least for short 2d distances (e.g. under a kilometer) it would be possible to consider `3d_dist = sqrt(2d_dist² + h_dist²)`
> 
> Or is this a bad idea?

My concern is that it might be way less accurate that the current geodesic calculation for lat-lon, especially for long distances. One might expect that the accuracy between the three would be the same.

**Comment by KostyaEsmukov** [comment]
Pushed https://github.com/geopy/geopy/commit/cd3fbafeabf06ce55320fefb8150155242839497 which documents the issue and adds a deprecation warning when altitudes are different to the upcoming geopy 1.23.0. In 2.x the different altitudes would raise a ValueError, which would be much easier to spot.

The `3d_dist = sqrt(2d_dist² + h_dist²)` formula might work fine for short distances, and it has been documented in this commit as a possible solution to the problem.

Adding a full support for calculating elevation doesn't seem viable to me at this moment, because I can't vouch for the mathematical accuracy of the implementation.

I'm closing this for now, but any ideas (preferably backed up by some theory) about adding full support for different altitudes are welcome.
