### ISSUE TITLE
Drop Python 2 support sooner than later?

### ISSUE THREAD

**Issue by deeplook** [geopy/geopy#389]
This would make some things easier I noticed, like use f-strings...

**Comment by KostyaEsmukov** [comment]
Python 2 support will be dropped in geopy 2.0: #335

This is a breaking change, so it won't happen in geopy 1.x, given that the project follows semver: https://geopy.readthedocs.io/en/1.21.0/#semver

f-strings will not be possible to be used in geopy 2.0 either, since it will support Python 3.5, which doesn't have f-strings.
