### ISSUE TITLE
[geocode] TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by quoidautre** [geopy/geopy#412]
Hello,

I try to use geopy (our own Nominatim server) with this code, and I've a problem : 
```
$ python -V
Python 3.6.9

$ python -m pip freeze
aenum==2.2.1
certifi==2019.6.16
chardet==3.0.4
future==0.18.2
geographiclib==1.49
geopy==1.20.0
idna==2.8
jsonpatch==1.23
jsonpointer==2.0
numpy==1.17.2
pyproj==2.2.2
python-dateutil==2.8.1
requests==2.22.0
reverse-geocode==1.4
reverse-geocoder==1.5.1
scipy==1.3.1
six==1.14.0
urllib3==1.25.3

$ python test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    location=valabre.geocode("Paris")
  File "/home/users/env3.6/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 312, in geocode
    params = {'q': self.format_string % query}
TypeError: not all arguments converted during string formatting

$ cat test.py
#!/usr/bin/python3
# coding: utf-8

from geopy.geocoders import Nominatim
valabre=Nominatim("domain=our_nominatim_server",scheme='http',user_agent="our_user_agent")

location=valabre.geocode("Paris")
print((location.latitude, location.longitude))

``` 

Have you an idea please ?
Regards,
F.

**Comment by KostyaEsmukov** [comment]
`Nominatim("domain=our_nominatim_server"` means "pass a string literal `domain=our_nominatim_server` as the first positional argument to [`Nominatim.__init__`](https://geopy.readthedocs.io/en/stable/#geopy.geocoders.Nominatim.__init__)", which is a `format_string` param.

What you probably meant is to pass `domain` as a kwarg, i.e. 
```
valabre=Nominatim(domain="our_nominatim_server",scheme='http',user_agent="our_user_agent")
```

Also, please take a look at https://github.com/geopy/geopy/blob/master/CONTRIBUTING.md#reporting-issues which suggests to use Stack Overflow for asking questions instead of the issue tracker.

**Comment by quoidautre** [comment]
Hello,

Thanks :)

Have a nice day.
F.
