### ISSUE TITLE
Reverse geocoding output language change

### ISSUE THREAD

**Issue by liki1017** [geopy/geopy#452]
Dear all,
Is there a way to change the output language of reverse geocoding?
I would like to get the address in Korean. 
Thank you in advance.

**Comment by juangallostra** [comment]
@liki1017 just struggled with this issue myself (I was getting some addresses in Spanish and others in English). I found a workaround which worked in my case, but I am not sure it will work in your case.

I added the header `'Accept-Language': 'en'` in https://github.com/geopy/geopy/blob/76bb2b136d699df92c3b7263e1f5d3660c74de2b/geopy/geocoders/base.py#L233 so that it looks like:

```Python
self.headers = {
    'User-Agent': user_agent or options.default_user_agent,
    'Accept-Language': 'ko'
}
```

to try and force the answer language. It seems to work well if I force the language to english (`en`) , but not so well for Korean (`ko`). As an example, this is what I got for a pair of coordinates in France after forcing the `Accept-Language` header to `ko`:

`Le Fugeret, Castellane, Alpes-de-Haute-Provence, Provence-Alpes-Côte d'Azur, 프랑스 본토, 04240, 프랑스`

And this for a pair of coordinates in Spain:

`Torre de los Frailes, Bajo Aragón, 테루엘, Aragón, 44600, España`

I am not sure why some countries are being translated and some not.

**Comment by juangallostra** [comment]
@KostyaEsmukov is there any supported way of setting custom headers for the requests being made by a Nominatim instance? If not, would a PR adding this feature make sense? Or at least adding support for setting the `Accept-Language` header?

**Comment by KostyaEsmukov** [comment]
> As a matter of fact, this seems to be the suggested way of getting addresses in a specific language, as stated in the [Nominatim documentation](https://nominatim.org/release-docs/develop/api/Reverse/#language-of-results).

This sections tells that language can be specified with both `Accept-Language` header and an `accept-language` query arg.

In fact, the `language` param (see https://geopy.readthedocs.io/en/stable/#geopy.geocoders.Nominatim.reverse) does exactly the latter: https://github.com/geopy/geopy/blob/7d75ea6feb124817692e42db03f172e3193e2f53/geopy/geocoders/nominatim.py#L351-L352

And it seems to work:

```
In [3]: geolocator = Nominatim(user_agent='my_email@myserver.com')

In [4]: geolocator.reverse('44.0041444,6.6407753', language='ko')
Out[4]: Location(Rue de la Tourre, Le Fugeret, Castellane, Alpes-de-Haute-Provence, Provence-Alpes-Côte d'Azur, 프랑스 본토, 04240, 프랑스, (44.00414666173156, 6.640775440922201, 0.0))

In [5]: geolocator.reverse('44.0041444,6.6407753', language='es')
Out[5]: Location(Rue de la Tourre, Le Fugeret, Castellane, Alpes de Alta Provenza, Provenza-Alpes-Costa Azul, Francia metropolitana, 04240, Francia, (44.00414666173156, 6.640775440922201, 0.0))
```

So I believe there's nothing to be done here. 

Closing, but let me know if I'm missing something out.
