### ISSUE TITLE
Question: Why does the latitude change when moving at a bearing of 90 degrees? (GreatCircleDistance)

### ISSUE THREAD

**Issue by danjampro** [geopy/geopy#495]
Hello,

I am looking at the code here:
https://github.com/geopy/geopy/blob/af0eedcfeb4e3eec88f19e2f822e7f14ac3468eb/geopy/distance.py#L478

Perhaps naively, I would expect a bearing of 90 degrees to move along the longitudinal without any change in latitude. However, this is clearly not the case here. When `bearing=90`, the equation reduces to:

```
lat2 = asin(
    sin(lat1) * cos(d_div_r)
)
```
And so `lat1` != `lat2`. 

Can someone advise on why this is the case?
Thanks!

**Comment by cffk** [comment]
`bearing=90` is just the *initial* bearing of the track.  In order to stay on a *great* circle, the bearing will change and the track will cross the equator.  If the bearing is kept at 90&deg;, the track follows a *little* circle, the circle of latitude.  If you need to clarify your thinking, imagine the problem when your starting point is 10 m north of the south pole.

**Comment by danjampro** [comment]
Hi @cffk, thank you for your response, which makes a lot of sense. I had indeed confused the great circle distance with the "little" circle distance.
