### ISSUE TITLE
GEOCoder using IGN france

### ISSUE THREAD

**Issue by LaurentBerger** [geopy/geopy#496]
In doc there is a dead link https://geoservices.ign.fr/documentation/services-acces.html   in page https://geopy.readthedocs.io/en/latest/#ignfrance

I'm not a regular user of geopy but I think something has changed in ign api : 
_"Vous êtes titulaire ou utilisateur d'une clé d'accès aux services web antérieure au 20 juillet 2021 ?

Rassurez-vous, si votre clé était active au 20 juillet 2021, elle reste utilisable jusqu'au 1er février 2022 inclus, pour vous laisser suffisamment de temps pour migrer vers nos URL en libre accès.

Pour vous accompagner dans l'utilisation des services web, notre équipe support est à votre disposition via notre formulaire de contact.

Désormais, seul l'accès aux services web issus de données SCAN 25/100/OACI reste soumis à l'utilisation d'une clé personnelle, disponible via inscription sur ce site._
"
google translate 
_Do you hold or use a web services access key prior to July 20, 2021?

Rest assured, if your key was active on July 20, 2021, it remains usable until February 1, 2022 inclusive, to give you enough time to migrate to our free access URLs.

To assist you in the use of web services, our support team is at your disposal via our contact form.

From now on, only access to web services from SCAN 25/100 / ICAO data remains subject to the use of a personal key, available through registration on this site._ 
 
So now api_key mean nothing and may be URLs have changed

**Comment by lerela** [comment]
Required changes are dead simple as seen in this commit: https://github.com/geopy/geopy/commit/76634124a994302513934bd131576be9dd26d5a2

I'm not submitting a PR because I haven't had the time to fix the tests

**Comment by KostyaEsmukov** [comment]
Thank you @LaurentBerger for bringing this up, and thank you @lerela for providing a commit which made it so much easier for me to understand how to proceed.

I have removed usages of the api_key/user arguments so that their values are just ignored now. To be honest I'm not completely sure why did they abandon authentication (which is useful for the service providers for precise rate-limiting), but reading into the https://geoservices.ign.fr/actualites/2021-10-04-evolution-des-modalites-dacces-aux-services-web article I guess they really did.
