### ISSUE TITLE
Adding params to Nominatim reverse

### ISSUE THREAD

**Issue by pablojadz** [geopy/geopy#508]
Hi, 
Thanks for a great package.

Would a PR to include more params into Nominatim reverse be welcomed?

Please advice since I'm trying to follow the rules and help develop this further. Just cloned the repo, build tests as explained [here](https://github.com/geopy/geopy/blob/master/CONTRIBUTING.md) and tests are failing

**Comment by KostyaEsmukov** [comment]
Hi,

I'm afraid I'm not very responsive at the moment.

I'm going to close this issue as it's neither a bug nor a specific feature request, but if you're still willing to do that, you're welcome to start with a PR.

As for the failing tests, it's natural for them to degrade, because geocoding services change their responses at times, and the current tests expecting the previous results start failing. You're free to ignore the failures not introduced by your changes.
