### ISSUE TITLE
Update `default_ssl_context` documentation with solution to `self-signed certificate in certificate chain` issue

### ISSUE THREAD

**Issue by ehogan** [geopy/geopy#546]
Hello 👋 

I have been investigating an `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain` issue (see https://github.com/ESMValGroup/ESMValCore/issues/2012) that others have also reported via [Stack Overflow](https://stackoverflow.com/search?q=%5Bgeopy%5D+%22self+signed+certificate+in+certificate+chain%22).

I have a solution, and I was wondering whether it would be possible to update the GeoPy documentation with this information, to help others with this issue?

Our web proxy at work is configured to use self-signed certificates, which (I believe) would be correctly identified if [requests.Session().trust_env](https://github.com/geopy/geopy/blob/master/geopy/adapters.py#L397) was set to `True`. However, the following (written similarly to [other examples in the documentation](https://geopy.readthedocs.io/en/stable/#geopy.geocoders.options); scroll down to `default_ssl_context`) also solves the problem:

```
import ssl
import geopy.geocoders
ctx = ssl.create_default_context()
geopy.geocoders.options.default_ssl_context = ctx
```
then run:
```
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="test_ehogan")
geolocation = geolocator.geocode("Amsterdam")
```

Would it be possible to also update the "Pass `None` to use the interpreter’s defaults (that is to use the system’s trusted CA certificates)." sentence in the documentation for `default_ssl_context`, as this default setting doesn't work in the above case.

If it is agreed that this is an acceptable task I would be happy to have a go at creating a PR; please let me know! 😊

**Comment by KostyaEsmukov** [comment]
Hello, thank you for such a detailed explanation!

> which (I believe) would be correctly identified if [requests.Session().trust_env](https://github.com/geopy/geopy/blob/master/geopy/adapters.py#L397) was set to True.

I think I have an explanation for what might be happening here. The trust_env setting also causes requests to ignore the `REQUESTS_CA_BUNDLE` environment variable, which I assume is set in your environment. In this case, requests uses the bundled CA set from `certifi`. However, in your situation, this bundled CA set doesn't include the proxy's CA that's present in your system store. This is likely the reason why passing the plain `ssl.create_default_context()` must be helping.

In this situation, I believe, the best approach is to make requests use the system's CA store by default, rather than the certifi's bundle, similarly to the default urllib-based adapter. This would (hopefully) make the `Pass None to use the interpreter’s defaults (that is to use the system’s trusted CA certificates)` statement correct for your scenario as well.
