### ISSUE TITLE
Failing Adapter tests in environments with an HTTP proxy

### ISSUE THREAD

**Issue by dvzrv** [geopy/geopy#551]
Hi! While trying to rebuild 2.3.0 in the context of #550 I ran into a few failing tests (which I am now disabling):

[python-geopy-2.3.0-3-x86_64-check.log](https://github.com/geopy/geopy/files/12048653/python-geopy-2.3.0-3-x86_64-check.log)

**Comment by KostyaEsmukov** [comment]
Turns out there is an issue with the httpbin.org service, which seems to be unmaintained now: https://github.com/postmanlabs/httpbin/issues/702

I switched tests to httpbingo.org which I hope will be more stable.

The reason why these tests must do the remote lookups is because they need an https service with a certificate the system CA store trusts. The easiest way to get that is issuing a remote query to the Internet.

Let me add that for downstream packages I recommend running tests with the `--skip-tests-requiring-internet` option (see #413) to avoid this kind of hustle.
